name: employ
description: Employ es la nueva forma de distribuir y firmar recibos al instante. Chateá, 
             asesorate y capacitate sin mails y sin llamados. ¡Todo dentro de la App!
version: 4.5.9+88

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # [ FLUTTER VENDORS ]
  http: ^1.5.0

  # [ FIREBASE ]
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  firebase_analytics: ^9.3.8
  firebase_crashlytics: ^2.8.13
  firebase_performance: ^0.8.4+4
  # firebase_dynamic_links: ^6.1.10  # DISCONTINUED - temporary disabled for iOS build
  firebase_messaging: ^13.1.0
  firebase_database: ^9.1.7
  firebase_storage: ^10.3.11
  # google_mlkit_text_recognition: ^0.15.0  # Disabled for iOS compatibility with Firebase 9.6.0

  # [ VENDORS ]
  date_format: ^2.0.9
  timeago: ^3.7.1
  keyboard_actions: 4.2.0
  vibration: ^3.1.3  # Replacement for flutter_vibrate (AGP 8.x compatible)
  localstorage: ^5.0.0
  simple_gradient_text: ^1.3.0
  path_provider: ^2.0.15
  permission_handler: ^11.3.1
  flutter_local_notifications: ^19.4.2
  uuid: ^4.5.1
  flutter_masked_text2: 0.9.1
  share_plus: ^12.0.0
  fluttertoast: ^8.2.12
  # intl: ^0.19.0  # Managed by Flutter SDK
  pdf_render: ^1.4.12
  flutter_slidable: ^3.1.2
  package_info_plus: ^9.0.0
  device_info_plus: ^11.3.0
  store_redirect: ^2.0.4
  # flutter_native_image: 0.0.6+1  # Discontinued plugin with AGP 8.x namespace issues

  # [CAMERA & FILES]
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  file_picker: ^8.3.2
  image_cropper: ^9.1.0

  # [ MAPS ]
  google_maps_flutter: ^2.2.6
  # flutter_google_places: 0.3.0  # Removed due to AGP 8.x namespace issue with google_api_headers
  location: ^7.0.1
  url_launcher: ^6.1.11

  # [ Forked VENDORS ]
  fluro: 2.0.5
  # syncfusion_flutter_signaturepad: ^25.2.7  # Temporarily disabled for iOS build
  # syncfusion_flutter_pdf: ^25.2.7  # Temporarily disabled for iOS build
  flutter_pdfview: ^1.4.1+1
  pin_input_text_field: ^4.5.2
  lottie: ^3.0.0
  country_code_picker: ^3.4.0
  country_codes: ^3.3.0
  double_back_to_close_app: ^2.1.0
  flutter_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  copy_with_extension: ^5.0.2
  # flutter_dynamic_icon: ^2.1.0  # Temporarily disabled due to AGP 8.x namespace issue
  image: ^4.0.17
  # google_api_headers: ^1.5.0+1  # AGP 8.x namespace issue, not used in code
  open_filex: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  copy_with_extension_gen: ^5.0.2
  json_serializable: ^6.6.2
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  fonts:
    - family: Employ
      fonts:
        - asset: assets/fonts/Employ.ttf
    - family: PROREGULAR
      fonts:
        - asset: assets/fonts/SF/SFPro-Regular.otf
    - family: PROMEDIUM
      fonts:
        - asset: assets/fonts/SF/SFPro-Medium.otf
    - family: PRO
      fonts:
        - asset: assets/fonts/SF/SFPro.otf
    - family: COMPACT
      fonts:
        - asset: assets/fonts/SF/Display-Regular.otf
  assets:
    - assets/animation/loader.json
    - assets/animation/employ-intro.json
    - assets/animation/dot_animation.json
    - assets/animation/confetti.json
    - assets/images/
    - assets/images/icons/
    - assets/images/avatar/

module:
  androidX: true
